// ── Styles ────────────────────────────────────────────────────────────────────
const styles: Record<string, React.CSSProperties> = {
  page: {
    minHeight: "100vh",
    background: "#f8fafc",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "24px 16px",
    fontFamily: "'Inter', sans-serif",
    gap: 16,
  },
  header: {
    width: "100%",
    maxWidth: 480,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  card: {
    background: "#fff",
    borderRadius: 16,
    padding: "24px",
    width: "100%",
    maxWidth: 480,
    boxShadow: "0 1px 4px rgba(0,0,0,0.08)",
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  title: {
    fontSize: 22,
    fontWeight: 700,
    color: "#1e1b4b",
    margin: 0,
  },
  subtitle: {
    color: "#6b7280",
    margin: 0,
    fontSize: 15,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: "#111827",
    margin: 0,
  },
  label: {
    fontSize: 12,
    color: "#6b7280",
    margin: 0,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  address: {
    fontSize: 13,
    fontFamily: "monospace",
    color: "#1e1b4b",
    background: "#f1f5f9",
    padding: "8px 12px",
    borderRadius: 8,
    wordBreak: "break-all",
    margin: 0,
  },
  badge: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "#f5f3ff",
    color: "#6d28d9",
    padding: "6px 12px",
    borderRadius: 20,
    fontSize: 13,
    fontWeight: 500,
    width: "fit-content",
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    background: "#7c3aed",
    display: "inline-block",
  },
  input: {
    border: "1px solid #e5e7eb",
    borderRadius: 10,
    padding: "10px 14px",
    fontSize: 14,
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
    color: "#111827",
  },
  primaryBtn: {
    background: "#6d28d9",
    color: "#fff",
    border: "none",
    borderRadius: 10,
    padding: "12px",
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    width: "100%",
    transition: "opacity 0.2s",
  },
  ghostBtn: {
    background: "transparent",
    border: "1px solid #e5e7eb",
    borderRadius: 8,
    padding: "6px 14px",
    fontSize: 13,
    cursor: "pointer",
    color: "#6b7280",
  },
  error: {
    color: "#dc2626",
    fontSize: 13,
    margin: 0,
    background: "#fef2f2",
    padding: "8px 12px",
    borderRadius: 8,
  },
  txRow: {
    borderTop: "1px solid #f1f5f9",
    paddingTop: 12,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  txTo: {
    fontSize: 12,
    fontFamily: "monospace",
    color: "#6b7280",
    margin: 0,
    wordBreak: "break-all",
  },
  statusBadge: {
    fontSize: 12,
    fontWeight: 600,
    padding: "3px 10px",
    borderRadius: 20,
  },
  link: {
    fontSize: 12,
    color: "#6d28d9",
    textDecoration: "none",
  },
};

export default styles;